site_name: Typus
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  logo: https://assets.polli.ai/docs-brand/latest/wordmarks/typus.svg
  logo_dark: https://assets.polli.ai/docs-brand/latest/wordmarks/typus.svg
extra_css:
  - https://assets.polli.ai/docs-brand/latest/polli-brand.css
extra_javascript:
  - https://assets.polli.ai/docs-brand/latest/polli-brand.js
nav:
  - Home: index.md
  - Taxonomy Service:
      - Overview: taxonomy_service.md
      - Offline mode: offline_mode.md
      - expanded_taxa schema: expanded_taxa.md
  - Models: models.md
  - Geometry: geometry.md
  - Tracks: tracks.md
  - Elevation Service: elevation_service.md
  - Contributing: contributing.md
  - Ops Helpers: reference/ops.md
  - API Reference: reference/api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
markdown_extensions:
  - tables
  - admonition
