site_name: Typus
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
nav:
  - Home: index.md
  - Taxonomy Service:
      - Overview: taxonomy_service.md
      - Offline mode: offline_mode.md
      - expanded_taxa schema: expanded_taxa.md
  - Models: models.md
plugins: []
markdown_extensions:
  - tables
  - admonition
