name: Docs

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

jobs:
  deploy-docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install docs extras
        run: |
          python -m pip install -U pip
          pip install -e ".[docs]"
      - name: Build docs
        run: mkdocs build
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.POLLISERVE0_SSH_PRIVATE_KEY }}
      - name: Check SSH connectivity
        run: |
          echo "Checking SSH connectivity to docs host..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
            ${{ secrets.POLLISERVE0_SSH_USER }}@${{ secrets.POLLISERVE0_SSH_PUBLIC_HOST }} echo ok
      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            site/ ${{ secrets.POLLISERVE0_SSH_USER }}@${{ secrets.POLLISERVE0_SSH_PUBLIC_HOST }}:/var/www/docs.polli.ai/html/typus/
      - name: Upload built site as artifact on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
